---
title: "Julie Theme For Multiple Plots"
author: "E. Kovacs"
date: "16 July 2019"
output: html_document
---

# Load necessary packages

```{r what you need}

install.packages("tidyverse")
install.packages("janitor")
install.packages("skimr")
install.packages("stringr")
install.packages("data.table")
install.packages("ggthemes")
install.packages("RColorBrewer")
install.packages("gmodels")
install.packages("cowplot")


library(tidyverse) # use install.packages("tidyverse") if receive an error message
library(janitor) # use install.packages("janitor") if receive an error message
library(skimr)  # use install.packages("skimr") if receive an error message
library(stringr) # use install.packages("stringr") if receive an error message
library(data.table)
library(ggthemes)
library(RColorBrewer)
library(gmodels)
library(cowplot)

```

# Code for generating a single title/legend etc for a multiplot panel

```{r}
## This code produce one figure (MCMC_ModelV5.png) putting together p1, p2 and p3 (each of them composed of 2 graphics) without the legend. To have a unique common legend to all the graph I use “get_legend” and add it below. I also add common x and y axis 

library(cowplot)
# the plot_grid function arranges plots into a grid and labels them
# p1-p4 are the individual plots
                      
p_MCMC <- plot_grid(p1 + theme(legend.position = "none"),p2 + theme(legend.position = "none"),p3 + theme(legend.position = "none"), p4 + theme(legend.position = "none"), align = 'vh', hjust = -1, nrow = 4)

# get_legend creates a legend cmmon to all the graphs

legend_b <- get_legend(p2 + theme(legend.position="bottom"))

#create common x and y labels

y.grob <- textGrob("Parameter estimates", 
                   gp=gpar(fontsize=15), rot=90)

x.grob <- textGrob("MCMC Iterations", 
                   gp=gpar(fontsize=15))

p <- plot_grid(grid.arrange(arrangeGrob(p_MCMC, left = y.grob, bottom = x.grob)), legend_b, ncol = 1, rel_heights = c(1, .2))
#ggsave(plot = p,width=8, height=10, file = "C:\\Users\\vercello\\Dropbox\\GCI\\Catlin\\Research projects\\Transitions\\PROJECT_CORAIL\\figures\\MCMC_ModelV5.png")

```

# The code above produces something like this:

